/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teletubbiescafe;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class OrderBetaPage extends javax.swing.JFrame {

    /**
     * Creates new form Orderpage
     */
    public OrderBetaPage() {
        initComponents();
    }
    
    DefaultListModel model = new DefaultListModel();
    DefaultTableModel model1 = new DefaultTableModel();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toppanel = new javax.swing.JPanel();
        cafenametext = new java.awt.Label();
        empfname = new javax.swing.JLabel();
        emplname = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        menupanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menulist = new javax.swing.JList<>();
        bottompanel = new javax.swing.JPanel();
        subtotaltext = new java.awt.Label();
        subtotalbox = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toppanel.setBackground(new java.awt.Color(255, 51, 0));

        cafenametext.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cafenametext.setForeground(new java.awt.Color(255, 255, 255));
        cafenametext.setText("Teletubbie's Cafe");

        empfname.setText("ทักษิณ");

        emplname.setText("ชินวัตร");

        logout.setText("Log Out");

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cafenametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empfname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emplname)
                .addGap(39, 39, 39)
                .addComponent(logout)
                .addGap(21, 21, 21))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cafenametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empfname)
                    .addComponent(emplname)
                    .addComponent(logout))
                .addContainerGap())
        );

        menupanel.setBackground(new java.awt.Color(204, 204, 204));
        menupanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menulist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menulist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Hamburger", "Fried Rice", "Chicken Wings", "Big Salad", "Omelet", "Pancake", "Waffle", "Soi Ju", "Som Tam", "Noodle", "Mama", "Spaghetti", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        menulist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menulistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(menulist);

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        bottompanel.setBackground(new java.awt.Color(255, 51, 0));

        subtotaltext.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        subtotaltext.setForeground(new java.awt.Color(255, 255, 255));
        subtotaltext.setText("Subtotal");

        subtotalbox.setBackground(new java.awt.Color(255, 51, 0));
        subtotalbox.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        subtotalbox.setForeground(new java.awt.Color(255, 255, 255));

        button1.setBackground(new java.awt.Color(255, 102, 0));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 0));
        button1.setLabel("Complete Order");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottompanelLayout = new javax.swing.GroupLayout(bottompanel);
        bottompanel.setLayout(bottompanelLayout);
        bottompanelLayout.setHorizontalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottompanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bottompanelLayout.createSequentialGroup()
                        .addComponent(subtotaltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtotalbox, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        bottompanelLayout.setVerticalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottompanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subtotalbox)
                    .addComponent(subtotaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        ordertable.setBorder(new javax.swing.border.MatteBorder(null));
        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane2.setViewportView(ordertable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottompanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottompanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void menulistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menulistMouseClicked
        // TODO add your handling code here:
        int sum = 0;
        int price;
        int quantity;
        int total;
        
        int food = menulist.getSelectedIndex();
        
        if(food == 0){
            price = 80;//get from database
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Hamburger",//get from database
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 1){
            price = 50;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Fried Rice",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 2){
            price = 40;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Chicken Wings",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 3){
            price = 40;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Big Salad",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 4){
            price = 35;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Omelet",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 5){
            price = 30;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Pancake",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 6){
            price = 45;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Waffle",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 7){
            price = 50;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Som Tam",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 8){
            price = 50;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Noodle",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 9){
            price = 30;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Mama",
                price,
                quantity,
                total
            }
            );
        }
        
        else if(food == 10){
            price = 50;
            quantity = Integer.parseInt(JOptionPane.showInputDialog("Enter the Quantity"));
            model1 = (DefaultTableModel)ordertable.getModel();
            total = price * quantity;
            
            model1.addRow(new Object[]{
                "Spaghetti",
                price,
                quantity,
                total
            }
            );
        }
        
        for(int i = 0 ; i < ordertable.getRowCount() ; i++){
            sum = sum + Integer.parseInt(ordertable.getValueAt(i,3).toString());
        }
        
        subtotalbox.setText(String.valueOf(sum));
        
        
    }//GEN-LAST:event_menulistMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderBetaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderBetaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderBetaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderBetaPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderBetaPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bottompanel;
    private java.awt.Button button1;
    private java.awt.Label cafenametext;
    private javax.swing.JLabel empfname;
    private javax.swing.JLabel emplname;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logout;
    private javax.swing.JList<String> menulist;
    public javax.swing.JPanel menupanel;
    private javax.swing.JTable ordertable;
    private javax.swing.JTextField subtotalbox;
    private java.awt.Label subtotaltext;
    public javax.swing.JPanel toppanel;
    // End of variables declaration//GEN-END:variables
}
